//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperVigilanciaNegocio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaccion
    {
        public int Id { get; set; }
        public string Concepto { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> Valor { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> Usuario_ID { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
